// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt-NJw1NmU3BR2l4-dp4ibMpAeUxgHhVQ',
    appId: '1:199644663898:web:f8154391eb489625a10863',
    messagingSenderId: '199644663898',
    projectId: 'health-monitoring-app-4ddf0',
    authDomain: 'health-monitoring-app-4ddf0.firebaseapp.com',
    storageBucket: 'health-monitoring-app-4ddf0.appspot.com',
    measurementId: 'G-YY7BQJHRN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6EuX_qaV1G6JdXck1AyUMA6eNP8xT6E',
    appId: '1:199644663898:android:df4186e3548dfc85a10863',
    messagingSenderId: '199644663898',
    projectId: 'health-monitoring-app-4ddf0',
    storageBucket: 'health-monitoring-app-4ddf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBviZB5cEAOord8BM0a1OUCs-aE2ax0jEA',
    appId: '1:199644663898:ios:ae9e830da7f25b8ba10863',
    messagingSenderId: '199644663898',
    projectId: 'health-monitoring-app-4ddf0',
    storageBucket: 'health-monitoring-app-4ddf0.appspot.com',
    iosClientId: '199644663898-t7ljr3l07vrrjkf3ru9o3vfgc98udl2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBviZB5cEAOord8BM0a1OUCs-aE2ax0jEA',
    appId: '1:199644663898:ios:ae9e830da7f25b8ba10863',
    messagingSenderId: '199644663898',
    projectId: 'health-monitoring-app-4ddf0',
    storageBucket: 'health-monitoring-app-4ddf0.appspot.com',
    iosClientId: '199644663898-t7ljr3l07vrrjkf3ru9o3vfgc98udl2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23Project',
  );
}
